'use client';
import { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Download, BookOpen, Play, Zap, AlertCircle, X } from 'lucide-react';
import UploadZone from '@/components/forge/UploadZone';
import GeneratorControls from '@/components/generator/GeneratorControls';
import QuestionCard from '@/components/generator/QuestionCard';
import QuizRunner from '@/components/quiz/QuizRunner';
import type { Question, QuizSet, GenerationOptions, QuizMode } from '@/lib/types';
import type { SessionResult } from '@/components/quiz/QuizRunner';
import { createClient } from '@/lib/supabase/client';

type PageState = 'upload' | 'generate' | 'practice';

export default function GeneratePage() {
  const [pageState, setPageState] = useState<PageState>('upload');
  const [extractedText, setExtractedText] = useState('');
  const [fileName, setFileName] = useState('');
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const [quizSet, setQuizSet] = useState<QuizSet | null>(null);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [quizMode, setQuizMode] = useState<QuizMode>('practice');
  const [sessionStarted, setSessionStarted] = useState(false);
  const [generationMode, setGenerationMode] = useState<'pdf' | 'topic'>('pdf');

  const handleTextExtracted = useCallback((text: string, name: string) => {
    setExtractedText(text);
    setFileName(name);
    setPageState('generate');
  }, []);

  const handleGenerate = useCallback(async (
    options: GenerationOptions,
    title: string,
    subject: string,
    chapter: string,
    mode: 'pdf' | 'topic',
    classLevel: string,
    topic: string
  ) => {
    setGenerating(true);
    setError('');
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode,
          text: mode === 'pdf' ? extractedText : undefined,
          topic: mode === 'topic' ? topic : undefined,
          classLevel: mode === 'topic' ? classLevel : undefined,
          options,
          title,
          subject,
          chapter: mode === 'pdf' ? chapter : undefined,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Generation failed');
      setQuizSet(data.quizSet);
      setQuestions(data.questions);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Generation failed');
    } finally {
      setGenerating(false);
    }
  }, [extractedText]);

  const handleSessionComplete = useCallback(async (results: SessionResult[]) => {
    if (!quizSet) return;
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    const correct = results.filter(r => r.isCorrect).length;
    const accuracy = results.length > 0 ? (correct / results.length) * 100 : 0;
    const duration = results.reduce((s, r) => s + r.timeTakenSecs, 0);

    const { data: session } = await supabase.from('quiz_sessions').insert({
      user_id: user.id,
      quiz_set_id: quizSet.id,
      mode: quizMode,
      score: correct,
      accuracy,
      duration_secs: duration,
      completed: true,
      completed_at: new Date().toISOString(),
    }).select().single();

    if (session) {
      const answers = results.map(r => ({
        session_id: session.id,
        question_id: r.questionId,
        user_id: user.id,
        user_answer: r.userAnswer,
        is_correct: r.isCorrect,
        time_taken_secs: r.timeTakenSecs,
      }));
      await supabase.from('session_answers').insert(answers);
    }
  }, [quizSet, quizMode]);

  const exportPDF = async () => {
    if (!questions.length) return;
    const jsPDF = (await import('jspdf')).default;
    const doc = new jsPDF();
    const title = quizSet?.title || 'Theorem Quiz';

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120);
    doc.text(`Generated by Theorem · ${questions.length} Questions`, 14, 28);
    doc.setTextColor(0);

    let y = 38;
    questions.forEach((q, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      const qText = `Q${i + 1}. [${q.question_type.toUpperCase()} · ${q.difficulty} · ${q.marks}M] ${q.question_text}`;
      const lines = doc.splitTextToSize(qText, 182);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 3;

      if (q.options) {
        doc.setFont('helvetica', 'normal');
        (q.options as { label: string; text: string }[]).forEach(opt => {
          if (y > 270) { doc.addPage(); y = 20; }
          const optText = `   ${opt.label}. ${opt.text}`;
          const optLines = doc.splitTextToSize(optText, 178);
          doc.text(optLines, 14, y);
          y += optLines.length * 5 + 1;
        });
      }
      y += 5;
    });

    // Answer key on last page
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Answer Key', 14, 20);
    y = 30;
    questions.forEach((q, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      const ans = q.options
        ? `Q${i + 1}. ${(q.options as { label: string; is_correct: boolean }[]).find(o => o.is_correct)?.label || q.answer}`
        : `Q${i + 1}. ${q.answer}`;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(ans, 182);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 2;
    });

    doc.save(`${title.replace(/\s+/g, '_')}_theorem.pdf`);
  };

  return (
    <div style={{ padding: '2rem', maxWidth: 1100 }}>
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '1.75rem', marginBottom: '0.35rem' }}>Generator Workspace</h1>
        <p>Upload study material and forge CBSE-style questions with AI.</p>
      </motion.div>

      {error && (
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', borderRadius: 'var(--radius)', padding: '0.875rem 1rem', marginBottom: '1.5rem' }}>
          <AlertCircle size={16} color="var(--error)" />
          <p style={{ color: '#f87171', fontSize: '0.875rem', flex: 1, margin: 0 }}>{error}</p>
          <button onClick={() => setError('')} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', display: 'flex' }}><X size={15} /></button>
        </div>
      )}

      {/* Practice mode runner */}
      {sessionStarted && questions.length > 0 ? (
        <div>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
            <h2 style={{ fontSize: '1.1rem' }}>{quizMode === 'practice' ? 'Practice Mode' : 'Exam Mode'}</h2>
            <button className="btn btn-ghost btn-sm" onClick={() => setSessionStarted(false)}><X size={14} /> Exit</button>
          </div>
          <QuizRunner
            questions={questions}
            mode={quizMode}
            timeLimitMinutes={30}
            onComplete={handleSessionComplete}
          />
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
          {/* Left: Upload + Preview */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {generationMode === 'pdf' && (
              <div className="card">
                <h3 style={{ fontSize: '0.9rem', marginBottom: '1rem' }}>
                  {pageState === 'upload' ? 'Upload Material' : `📄 ${fileName}`}
                </h3>
                {pageState === 'upload' ? (
                  <UploadZone onTextExtracted={handleTextExtracted} />
                ) : (
                  <div>
                    <div style={{ background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', padding: '1rem', maxHeight: 320, overflowY: 'auto', fontSize: '0.82rem', lineHeight: 1.7, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                      {extractedText.slice(0, 3000)}{extractedText.length > 3000 ? '\n\n[…truncated for preview]' : ''}
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '0.75rem' }}>
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{extractedText.split(/\s+/).length.toLocaleString()} words extracted</span>
                      <button className="btn btn-ghost btn-sm" onClick={() => { setPageState('upload'); setExtractedText(''); setQuestions([]); setQuizSet(null); }}>
                        Replace file
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Questions output */}
            {questions.length > 0 && (
              <div className="card">
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1rem', flexWrap: 'wrap', gap: '0.5rem' }}>
                  <h3 style={{ fontSize: '0.9rem' }}>{questions.length} Questions Generated</h3>
                  <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                    <button className="btn btn-ghost btn-sm" onClick={exportPDF}><Download size={13} /> Export PDF</button>
                    <button className="btn btn-ghost btn-sm" onClick={() => { setQuizMode('practice'); setSessionStarted(true); }}><Play size={13} /> Practice</button>
                    <button className="btn btn-primary btn-sm" onClick={() => { setQuizMode('exam'); setSessionStarted(true); }}><BookOpen size={13} /> Exam Mode</button>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Right: Controls */}
          <div className="card">
            <GeneratorControls
              onGenerate={handleGenerate}
              loading={generating}
              pdfUploaded={!!extractedText}
              mode={generationMode}
              onModeChange={setGenerationMode}
            />
          </div>
        </div>
      )}

      {/* Questions list */}
      {!sessionStarted && questions.length > 0 && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}
        >
          {questions.map((q, i) => (
            <QuestionCard key={q.id} question={q} index={i} />
          ))}
        </motion.div>
      )}

      {/* Generating shimmer */}
      {generating && (
        <div style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {[1,2,3,4,5].map(i => (
            <div key={i} className="shimmer" style={{ height: 100, borderRadius: 'var(--radius-lg)', animationDelay: `${i * 0.1}s` }} />
          ))}
          <div style={{ textAlign: 'center', marginTop: '0.5rem' }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', color: 'var(--ember)', fontSize: '0.875rem' }}>
              <Zap size={14} />
              <span>Forging your questions… This may take 15–30 seconds.</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
