'use client';
import Link from 'next/link';
import ThemeToggle from '@/components/ui/ThemeToggle';
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import InteractiveDemo from '@/components/landing/InteractiveDemo';
import MagneticButton from '@/components/ui/MagneticButton';
import { ChevronDown, Upload, Cpu, BarChart2, BookOpen, Zap, Shield, Menu, X } from 'lucide-react';
import TheoremLogo from '@/components/ui/TheoremLogo';
import dynamic from 'next/dynamic';

const DotField = dynamic(() => import('@/components/ui/DotField'), { ssr: false });
const SideRays = dynamic(() => import('@/components/ui/SideRays'), { ssr: false });

const FEATURES = [
  { icon: Upload, title: 'Smart PDF Upload', desc: 'Drag & drop PDFs. We extract text, identify subject and chapter, and find key concepts automatically.' },
  { icon: Cpu, title: 'AI Question Engine', desc: 'Generates authentic MCQs, short answers, HOTS, case-based, and assertion-reason questions.' },
  { icon: Zap, title: 'Three Quiz Modes', desc: 'Practice with instant feedback, simulate exams with a timer, or let adaptive mode adjust to your level.' },
  { icon: BarChart2, title: 'Deep Analytics', desc: 'Track accuracy, weak concepts, and time per question. Get AI-powered insights on what to revise.' },
  { icon: BookOpen, title: 'Study Notes & Flashcards', desc: 'Generate comprehensive notes and spaced-repetition flashcards from any material — instantly.' },
  { icon: Shield, title: 'Curriculum Aligned', desc: 'Every question is generated with strict syllabus relevance enforced — no hallucinations.' },
];

const HOW_IT_WORKS = [
  { step: '01', title: 'Upload Your Material', desc: 'Drop a PDF, notes excerpt, or chapter summary into the forge.' },
  { step: '02', title: 'AI Reads & Understands', desc: 'The platform extracts text, identifies subject, chapter, and key concepts.' },
  { step: '03', title: 'Questions Generated', desc: 'High-quality practice questions emerge — organised by difficulty and type, ready to practice.' },
];

const FAQS = [
  { q: 'What file types can I upload?', a: 'Currently PDF files are supported. The system extracts text from standard PDFs — scanned or image-only PDFs will have limited extraction.' },
  { q: 'How many questions can I generate at once?', a: 'You can generate between 5 and 50 questions per session. Use the slider in the generator to set your count.' },
  { q: 'Are the questions actually curriculum-aligned?', a: 'Yes. The AI is prompted specifically to follow board wording conventions, difficulty calibration, and question formats.' },
  { q: 'Can I export the questions as a PDF?', a: 'Absolutely. After generation, hit Export to download a formatted PDF worksheet with or without an answer key.' },
  { q: 'Is my uploaded content stored securely?', a: 'All uploads are stored in your private Supabase bucket, protected by row-level security. Only you can access your files.' },
];

const REVIEWS = [
  { text: "I cut my weekly revision and quiz-prep time from four hours to forty minutes. The questions look exactly like my actual board papers.", author: "Arjun", role: "Class 12 Science" },
  { text: "I used Theorem while preparing for JEE. The targeted practice and AI feedback really helped improve my performance. I highly recommend it to anyone preparing for competitive exams.", author: "Deepesh", role: "JEE Adv. AIR 3095", special: true },
  { text: "I used Theorum to analyze my performance across practice sets, and the ability to adjust question difficulty based on my aptitude made every session focused and genuinely productive.", author: "Yash", role: "NEET AIR 7173", special: true },
  { text: "The assertion-reason questions generated by Theorem are incredibly accurate. It's the only AI tool I trust for my students.", author: "Dr. Sharma", role: "Professor of Biology" },
  { text: "I used to dread finding practice questions for my exams. Now I just upload the chapter and I'm ready to study in seconds.", author: "Priya", role: "Class 10 Student" },
  { text: "The detailed analytics helped me identify exactly which concepts I was weak in. My test scores have improved drastically.", author: "Rahul", role: "University Freshman" },
  { text: "Finally, an AI tool that actually understands the nuances of syllabus requirements instead of hallucinating random trivia.", author: "Ananya", role: "Class 11 Commerce" },
  { text: "This is the smartest way I've ever prepared for finals. The flashcards feature is an absolute lifesaver.", author: "Kiran", role: "Class 12 Humanities" }
];

function Navbar() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    const handler = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', handler);
    return () => window.removeEventListener('scroll', handler);
  }, []);

  return (
    <nav style={{
      position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
      background: scrolled || menuOpen ? 'var(--surface-glass)' : 'transparent',
      backdropFilter: scrolled || menuOpen ? 'blur(24px)' : 'none',
      WebkitBackdropFilter: scrolled || menuOpen ? 'blur(24px)' : 'none',
      borderBottom: scrolled || menuOpen ? '1px solid var(--border)' : '1px solid transparent',
      boxShadow: scrolled || menuOpen ? '0 1px 2px rgba(0,0,0,0.05), inset 0 -1px 0 rgba(255,255,255,0.1)' : 'none',
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    }}>
      <div className="container" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '64px', paddingLeft: 'clamp(1rem, 5vw, 1.5rem)', paddingRight: 'clamp(1rem, 5vw, 1.5rem)' }}>
        
        <div className="flex items-center gap-3">
          {/* Hamburger (Mobile only) */}
          <button className="md:hidden btn btn-ghost btn-icon" onClick={() => setMenuOpen(!menuOpen)} style={{ padding: '0.25rem', marginLeft: '-0.25rem' }}>
            {menuOpen ? <X size={20} /> : <Menu size={20} />}
          </button>
          
          <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', textDecoration: 'none' }}>
            <div style={{ width: 28, height: 28, background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 6, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <TheoremLogo size={16} color="var(--text)" />
            </div>
            <span className="hidden sm:block" style={{ fontWeight: 700, fontSize: '1.1rem', color: 'var(--text)', letterSpacing: '-0.02em' }}>Theorem</span>
          </Link>
        </div>

        {/* Desktop Links */}
        <div className="hidden md:flex items-center gap-1">
          <Link href="#features" className="btn btn-ghost btn-sm">Features</Link>
          <Link href="#how-it-works" className="btn btn-ghost btn-sm">How it works</Link>
          <Link href="/about" className="btn btn-ghost btn-sm">About</Link>
        </div>

        {/* Right Actions */}
        <div className="flex items-center gap-1.5 sm:gap-3">
          <ThemeToggle />
          <div style={{ width: '1px', height: '24px', background: 'var(--border)' }} className="hidden md:block" />
          <Link href="/login" className="btn btn-ghost btn-sm">Sign in</Link>
          <MagneticButton asLink href="/signup" className="btn btn-primary btn-sm" style={{ padding: '0.4rem 0.75rem' }}>
            <span className="hidden sm:inline">Start for free</span>
            <span className="sm:hidden">Start</span>
          </MagneticButton>
        </div>
      </div>

      {/* Mobile Menu Dropdown */}
      <AnimatePresence>
        {menuOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="md:hidden"
            style={{ overflow: 'hidden', background: 'var(--surface)' }}
          >
            <div style={{ padding: '1rem 1.5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem', borderBottom: '1px solid var(--border)' }}>
              <Link href="#features" onClick={() => setMenuOpen(false)} className="btn btn-ghost" style={{ justifyContent: 'flex-start' }}>Features</Link>
              <Link href="#how-it-works" onClick={() => setMenuOpen(false)} className="btn btn-ghost" style={{ justifyContent: 'flex-start' }}>How it works</Link>
              <Link href="/about" onClick={() => setMenuOpen(false)} className="btn btn-ghost" style={{ justifyContent: 'flex-start' }}>About</Link>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </nav>
  );
}

function AccordionItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="accordion-item">
      <button className="accordion-trigger" onClick={() => setOpen(!open)}>
        <span>{q}</span>
        <ChevronDown size={18} style={{ transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.3s', color: 'var(--text-muted)', flexShrink: 0 }} />
      </button>
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            style={{ overflow: 'hidden' }}
          >
            <p style={{ paddingBottom: '1.25rem', lineHeight: 1.7 }}>{a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function HeroDotField() {
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    const update = () => {
      const isDark = document.documentElement.classList.contains('dark');
      setIsDarkMode(isDark);
    };
    update();
    const observer = new MutationObserver(update);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);

  const gradientFrom = isDarkMode ? 'rgba(124, 157, 150, 0.6)' : 'rgba(70, 95, 90, 0.95)'; // darker for light mode
  const gradientTo = isDarkMode ? 'rgba(98, 128, 122, 0.4)' : 'rgba(50, 75, 70, 0.85)'; // darker for light mode
  const glowColor = isDarkMode ? 'rgba(124, 157, 150, 0.15)' : 'rgba(124, 157, 150, 0.12)';
  const dotRadius = isDarkMode ? 1.5 : 2.2;

  return (
    <DotField
      dotRadius={dotRadius}
      dotSpacing={14}
      cursorRadius={500}
      cursorForce={0.1}
      bulgeOnly={true}
      bulgeStrength={67}
      glowRadius={200}
      sparkle={true}
      waveAmplitude={0}
      gradientFrom={gradientFrom}
      gradientTo={gradientTo}
      glowColor={glowColor}
    />
  );
}

function HeroSideRays() {
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    const update = () => {
      const isDark = document.documentElement.classList.contains('dark');
      setIsDarkMode(isDark);
    };
    update();
    const observer = new MutationObserver(update);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);

  const rayColor1 = isDarkMode ? '#7C9D96' : '#62807A'; // --ember / --ember-dim
  const rayColor2 = isDarkMode ? '#94B8B0' : '#7C9D96'; // --ember-glow / --ember
  const intensity = isDarkMode ? 1.5 : 2.0;

  return (
    <SideRays
      speed={2.5}
      rayColor1={rayColor1}
      rayColor2={rayColor2}
      intensity={intensity}
      spread={2}
      origin="top-right"
      tilt={0}
      saturation={1.5}
      blend={0.75}
      falloff={1.6}
      opacity={0.6}
    />
  );
}

export default function LandingPage() {

  return (
    <>
      <Navbar />

      {/* ── HERO ── */}
      <section style={{
        minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center',
        position: 'relative', overflow: 'hidden',
      }}>
        {/* SideRays Background (Behind DotField) */}
        <div style={{ position: 'absolute', inset: 0, zIndex: 0 }}>
          <HeroSideRays />
        </div>
        
        {/* DotField Background */}
        <div style={{ position: 'absolute', inset: 0, zIndex: 1 }}>
          <HeroDotField />
        </div>

        {/* Hero Content */}
        <div style={{ position: 'relative', zIndex: 10, width: '100%' }} className="container mx-auto px-6 pt-32 pb-24 text-center flex flex-col items-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
            style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '2.5rem' }}
          >
            <h1 className="hero-title" style={{ lineHeight: 1.1 }}>
              The <span style={{ color: 'var(--ember)' }}>Smarter</span> Way to Revise <br className="hidden md:block" />
              <span style={{ color: 'var(--highlight)' }}>Any Topic</span>
            </h1>

            <MagneticButton asLink href="/signup" className="btn btn-primary btn-lg" style={{ fontSize: '1.1rem', padding: '1rem 2.5rem' }}>
              Start for free
            </MagneticButton>
          </motion.div>
        </div>
      </section>

      <section className="section" style={{ background: 'var(--bg)' }}>
        <InteractiveDemo />
      </section>

      {/* ── ARCHITECTURE OF TRUST ── */}
      <section style={{ padding: '4rem 0', background: 'var(--surface-2)', borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)', overflow: 'hidden' }}>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', gap: '2.5rem' }}>
          
          {/* Looping Marquee */}
          <div style={{ width: '100%', position: 'relative' }}>
            <div style={{ display: 'flex', gap: '1.5rem', width: 'max-content', padding: '0 1rem' }} className="animate-scroll">
              {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
              {[...REVIEWS, ...REVIEWS].map((r: any, i) => (
                <div key={i} className="card" style={{ width: 'min(380px, 85vw)', flexShrink: 0, display: 'flex', flexDirection: 'column', gap: '1.25rem', whiteSpace: 'normal', textAlign: 'left', background: 'var(--surface)', ...(r.special ? { border: '1px solid var(--ember-border)', boxShadow: 'var(--glow-ember)', position: 'relative', zIndex: 1 } : {}) }}>
                  <p style={{ fontFamily: 'var(--font-serif)', fontSize: '1.1rem', color: 'var(--text)', lineHeight: 1.5 }}>&quot;{r.text}&quot;</p>
                  <div style={{ marginTop: 'auto' }}>
                    <div style={{ fontWeight: 600, color: 'var(--text)' }}>{r.author}</div>
                    <div style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>{r.role}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem' }}>
            <div style={{ width: 40, height: 1, background: 'var(--border-2)' }} />
            <p style={{ fontSize: '0.875rem', color: 'var(--text-dim)', letterSpacing: '0.05em', textTransform: 'uppercase', fontWeight: 600 }}>
              Trusted by 4300+ students and educators
            </p>
          </div>

        </div>
      </section>

      {/* ── HOW IT WORKS (Spacious Layout) ── */}
      <section id="how-it-works" className="section">
        <div className="container" style={{ maxWidth: 800 }}>
          <div style={{ marginBottom: '6rem' }}>
            <h2 style={{ fontSize: 'clamp(2.5rem, 5vw, 4rem)', marginBottom: '1.5rem', letterSpacing: '-0.03em' }}>The simplest path to practice.</h2>
            <p className="editorial-text">
              No complicated prompt engineering. No fighting with generic AI to match your syllabus. Just your material, transformed into mastery.
            </p>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '4rem' }}>
            {HOW_IT_WORKS.map((step) => (
              <motion.div
                key={step.step}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                style={{ display: 'flex', gap: '2rem', alignItems: 'flex-start' }}
              >
                <div style={{
                  fontSize: '3rem', fontWeight: 700,
                  color: 'var(--border-2)',
                  fontFamily: 'var(--font-serif)',
                  lineHeight: 1,
                  marginTop: '-0.25rem'
                }}>
                  {step.step}
                </div>
                <div>
                  <h3 style={{ fontSize: '1.75rem', marginBottom: '0.75rem', letterSpacing: '-0.02em' }}>{step.title}</h3>
                  <p className="editorial-text" style={{ fontSize: '1.1rem' }}>{step.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section id="features" className="section diagonal-bg" style={{ background: 'var(--surface-2)' }}>
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: '3.5rem' }}>
            <div className="badge badge-ember" style={{ marginBottom: '1rem' }}>Features</div>
            <h2>Everything you need to practice smarter</h2>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(280px, 100%), 1fr))', gap: '1.25rem' }}>
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="card card-ember"
              >
                <div style={{
                  width: 44, height: 44, borderRadius: 8,
                  background: 'var(--ember-subtle)',
                  border: '1px solid var(--ember-border)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  marginBottom: '1rem',
                }}>
                  <f.icon size={20} color="var(--ember)" />
                </div>
                <h3 style={{ marginBottom: '0.5rem' }}>{f.title}</h3>
                <p style={{ fontSize: '0.875rem', lineHeight: 1.6 }}>{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="section">
        <div className="container" style={{ maxWidth: 700, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
            <div className="badge badge-ember" style={{ marginBottom: '1rem' }}>FAQ</div>
            <h2>Common questions</h2>
          </div>
          <div style={{ border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', padding: '0 1.5rem', background: 'var(--surface)' }}>
            {FAQS.map((faq) => (
              <AccordionItem key={faq.q} q={faq.q} a={faq.a} />
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA BANNER ── */}
      <section className="section" style={{ background: 'var(--surface-2)', borderTop: '1px solid var(--border)' }}>
        <div className="container" style={{ textAlign: 'center', maxWidth: 600 }}>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          >
            <h2 style={{ fontSize: 'clamp(3rem, 6vw, 4.5rem)', marginBottom: '1.5rem', letterSpacing: '-0.04em', lineHeight: 1 }}>
              Stop reading. <br/> Start practicing.
            </h2>
            <p className="editorial-text" style={{ margin: '0 auto 3rem', maxWidth: 480 }}>
              The best way to understand Theorem is to see it generate your first assessment.
            </p>
            <MagneticButton asLink href="/signup" className="btn btn-primary btn-lg" style={{ fontSize: '1.1rem', padding: '1rem 3rem' }}>
              Start for free
            </MagneticButton>
          </motion.div>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer style={{
        borderTop: '1px solid var(--border)',
        padding: '2rem 0',
        background: 'var(--bg)',
      }}>
        <div className="container" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <div style={{ width: 22, height: 22, background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 5, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <TheoremLogo size={12} color="var(--text)" />
            </div>
            <span style={{ fontWeight: 700, fontSize: '0.9rem', color: 'var(--text-muted)' }}>Theorem</span>
          </div>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>
            Where learning is forged through practice.
          </p>
          <div style={{ display: 'flex', gap: '1.5rem' }}>
            <Link href="/feedback" style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textDecoration: 'none' }} onMouseEnter={e => (e.currentTarget.style.color = 'var(--text)')} onMouseLeave={e => (e.currentTarget.style.color = 'var(--text-muted)')}>Leave Feedback</Link>
            <Link href="/about" style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textDecoration: 'none' }} onMouseEnter={e => (e.currentTarget.style.color = 'var(--text)')} onMouseLeave={e => (e.currentTarget.style.color = 'var(--text-muted)')}>About</Link>
            <Link href="/login" style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textDecoration: 'none' }} onMouseEnter={e => (e.currentTarget.style.color = 'var(--text)')} onMouseLeave={e => (e.currentTarget.style.color = 'var(--text-muted)')}>Sign in</Link>
          </div>
        </div>
      </footer>
    </>
  );
}
